### ISSUE TITLE
./deploy.sh fails to launch inference-server

### ISSUE THREAD

**Issue by iamgoutham** [microsoft/confidential-ai#11]
Inference server fails to start when a ACI container is launched.  Replacing inference-server with hello-app works fine(atleast is deploys). Seems like an issue with policy with hashes does not match when container is coming up
Below is the error.
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"message\": \"CodePackageActivation:inference-server:EntryPoint:133222546642575672'. 'There was an error during CodePackage activation.GrpcStatusCode=UNKNOWN, ErrorMessage=failed to create containerd task: failed to create shim task: failed to mount container storage: failed to add LCOW layer: failed to add SCSI layer: failed to modify UVM with new SCSI mount: guest modify: guest RPC failure: mounting scsi device controller 3 lun 30 onto /run/mounts/m44 denied by policy: mount_device not allowed by policy. Errors: [deviceHash not found]. Input: {\\\"deviceHash\\\":\\\"5da7b7e57848fae3af26a048e7851d7178ea3c6b2fb4faf59becd96883c8938d\\\",\\\"target\\\":\\\"/run/mounts/m44\\\"}: unknown'\\r\\n;The container group provisioning has failed. Refer to 'DeploymentFailedReason' event for more details.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]}}

**Comment by deuch** [comment]
I've exactly the same error

**Comment by deuch** [comment]
I've found the issue.
The az confcom acipolicygen has some bug and does not add the layers of the inference-server image in the policy. You can check that the tab [] is empty.

I've made a simple template with only the image of the inference server.
I've saved the imaeg as a tar (docker save inference-server image.tar) and use this command : 

az confcom acipolicygen -i /tmp/policy-in2.json --tar inference-server.tar --outraw-pretty-print

I retrieved all the layers of the image. I've created a policy file will all the informations and encoded it in base64.
In the different scripts, i use the content of my encoded policy file instead of the az confcom acipolicygen command.

Like : 

export CCE_POLICY=$(az confcom acipolicygen -i /tmp/policy-in.json) 

replaced by : 

export CCE_POLICY=$(cat cce_policy_b64)

Not pretty but it does the job.
Same thing with all python command, replaced by python3 (to be sure).

**Comment by jiazhang0** [comment]
> 

The reason why the layers of inference-server in the generated cce policy is empty may be caused by out-of-memory. Specifically, `az confcom acipolicygen` calls /root/.azure/cliextensions/confcom/azext_confcom/bin/dmverity-vhd （https://github.com/microsoft/hcsshim/blob/main/cmd/dmverity-vhd/README.md）to generate the root hashes for each layer. The larger the size of the container image, the greater the memory resources consumed by dmverity-vhd. If the amount of free memory cannot meet the requirements of dmverity-vhd, it will be killed by kernel due to out-of-memory.

```
Out of memory: Killed process 63188 (dmverity-vhd) total-vm:10521164kB, anon-rss:7144528kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:14088kB oom_score_adj:0
```

and thus the resulting "layers" field in the generated cce policy for inference-server image will be empty.

Simply make sure the free memory available up to 64GB.

**Comment by kapilvgit** [comment]
@iamgoutham can I consider this issue closed?

**Comment by iamgoutham** [comment]
Yes. You can close this issue
